/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment specification 'org.genivi.commonapi.core.deployment'
*******************************************************************************/
package org.genivi.commonapi.core;

import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'org.genivi.commonapi.core.deployment' specification
 *
 * @deprecated use class org.genivi.commonapi.core.Deployment.InterfacePropertyAccessor instead
 */
public class DeploymentInterfacePropertyAccessor
	extends org.genivi.commonapi.core.Deployment.InterfacePropertyAccessor
	implements org.genivi.commonapi.core.Deployment.Enums
{
	public DeploymentInterfacePropertyAccessor(FDeployedInterface target) {
		super(target);
	}
}
   
