name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run maven script
      uses: guillonapa/action-maven-cli/jdk8@master
      run: mvn -Dtarget.id=org.genivi.commonapi.core.target clean verify
