name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: '${{ github.workspace }}/capicxx-core-tools'
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build and package project
      run: mvn -Dtarget.id='${{ github.workspace }}'/capicxx-core-tools/org.genivi.commonapi.core.target clean verify
