name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: '${{ github.workspace }}/capicxx-core-tools'
    - name: Run maven script
      uses: guillonapa/action-maven-cli/jdk8@master
      with:
        lifecycle: '-Dtarget.id=${{ github.workspace }}/capicxx-core-tools/org.genivi.commonapi.core.target clean verify'
